# -----------------------------------------------------------------------------
# [container_queries]
# Defines named container query breakpoints.
# These are prefixed with '@' to distinguish them from screen breakpoints.
# e.g., "@md:text-lg"
# Format: name = "min-width value"
# -----------------------------------------------------------------------------
[container_queries]
"@xs" = "20rem"   # 320px
"@sm" = "24rem"   # 384px
"@md" = "28rem"   # 448px
"@lg" = "32rem"   # 512px
"@xl" = "36rem"   # 576px
"@2xl" = "42rem"  # 672px
"@3xl" = "48rem"  # 768px
"@4xl" = "56rem"  # 896px
"@5xl" = "64rem"  # 1024px
"@6xl" = "72rem"  # 1152px
"@7xl" = "80rem"  # 1280px
"@8xl" = "88rem"  # 1408px
"@9xl" = "96rem"  # 1536px
