#############################
# Custom CSS Properties Metadata
#
# Define custom properties that should be emitted as @property at-rules.
# These improve animation/interpolation & validation for CSS variables.
#
# Format:
# [properties]
# "--var-name" = { syntax = "<color>", inherits = false, initial = "#0000" }
#
# Fields:
#  syntax   : Type descriptor per CSS Properties & Values API (e.g. "*", "<color>", "<length>")
#  inherits : true/false (default false if omitted)
#  initial  : Optional initial-value (omit to skip line)
#
# NOTE: Keys MUST include the leading --.
#############################

[properties]
"--brand-hue" = { syntax = "<angle>", inherits = false, initial = "0deg" }
"--brand-accent" = { syntax = "<color>", inherits = false, initial = "#0000" }
"--spacing-scale" = { syntax = "<number>", inherits = false, initial = "1" }
"--easing-fn" = { syntax = "*", inherits = false, initial = "cubic-bezier(0.4,0,0.2,1)" }
"--dynamic-opacity" = { syntax = "<percentage>", inherits = false, initial = "100%" }
"--border-spacing-x" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--border-spacing-y" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--translate-x" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--translate-y" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--rotate" = { syntax = "<angle>", inherits = false, initial = "0deg" }
"--skew-x" = { syntax = "<angle>", inherits = false, initial = "0deg" }
"--skew-y" = { syntax = "<angle>", inherits = false, initial = "0deg" }
"--scale" = { syntax = "<number>", inherits = false, initial = "1" }
"--scale-x" = { syntax = "<number>", inherits = false, initial = "1" }
"--scale-y" = { syntax = "<number>", inherits = false, initial = "1" }
"--pan-x" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--pan-y" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--pinch-zoom" = { syntax = "<number>", inherits = false, initial = "1" }
"--scroll-snap-strictness" = { syntax = "*", inherits = false, initial = "proximity" }
"--gradient-from" = { syntax = "<color>", inherits = false, initial = "transparent" }
"--gradient-via" = { syntax = "<color>", inherits = false, initial = "transparent" }
"--gradient-to" = { syntax = "<color>", inherits = false, initial = "transparent" }
"--gradient-from-position" = { syntax = "<percentage>", inherits = false, initial = "0%" }
"--gradient-via-position" = { syntax = "<percentage>", inherits = false, initial = "50%" }
"--gradient-to-position" = { syntax = "<percentage>", inherits = false, initial = "100%" }
"--ordinal" = { syntax = "*", inherits = false, initial = "normal" }
"--slashed-zero" = { syntax = "*", inherits = false, initial = "normal" }
"--numeric-figures" = { syntax = "*", inherits = false, initial = "normal" }
"--numeric-spacing" = { syntax = "*", inherits = false, initial = "normal" }
"--numeric-fraction" = { syntax = "*", inherits = false, initial = "normal" }
"--ring-inset" = { syntax = "*", inherits = false, initial = "" }
"--ring-offset-width" = { syntax = "<length>", inherits = false, initial = "0px" }
"--ring-offset-color" = { syntax = "<color>", inherits = false, initial = "#fff" }
"--ring-color" = { syntax = "<color>", inherits = false, initial = "#3b82f6" }
"--ring-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--ring-offset-shadow" = { syntax = "<shadow>", inherits = false, initial = "0 0 #0000" }
"--ring-shadow" = { syntax = "<shadow>", inherits = false, initial = "0 0 #0000" }
"--shadow" = { syntax = "<shadow>", inherits = false, initial = "0 0 #0000" }
"--shadow-colored" = { syntax = "*", inherits = false, initial = "" }
"--shadow-color" = { syntax = "<color>", inherits = false, initial = "#000" }
"--blur" = { syntax = "<length>", inherits = false, initial = "0" }
"--brightness" = { syntax = "<number>", inherits = false, initial = "1" }
"--contrast" = { syntax = "<number>", inherits = false, initial = "1" }
"--grayscale" = { syntax = "<number>", inherits = false, initial = "0" }
"--hue-rotate" = { syntax = "<angle>", inherits = false, initial = "0deg" }
"--invert" = { syntax = "<number>", inherits = false, initial = "0" }
"--saturate" = { syntax = "<number>", inherits = false, initial = "1" }
"--sepia" = { syntax = "<number>", inherits = false, initial = "0" }
"--drop-shadow" = { syntax = "<shadow>", inherits = false, initial = "0 0 #0000" }
"--backdrop-blur" = { syntax = "<length>", inherits = false, initial = "0" }
"--backdrop-brightness" = { syntax = "<number>", inherits = false, initial = "1" }
"--backdrop-contrast" = { syntax = "<number>", inherits = false, initial = "1" }
"--backdrop-grayscale" = { syntax = "<number>", inherits = false, initial = "0" }
"--backdrop-hue-rotate" = { syntax = "<angle>", inherits = false, initial = "0deg" }
"--backdrop-invert" = { syntax = "<number>", inherits = false, initial = "0" }
"--backdrop-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--backdrop-saturate" = { syntax = "<number>", inherits = false, initial = "1" }
"--backdrop-sepia" = { syntax = "<number>", inherits = false, initial = "0" }
"--background-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--border-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--text-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--fill-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--stroke-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--perspective" = { syntax = "<length>", inherits = false, initial = "0" }
"--content" = { syntax = "*", inherits = false, initial = "''" }
"--caret-color" = { syntax = "<color>", inherits = true, initial = "auto" }
"--accent-color" = { syntax = "<color>", inherits = true, initial = "auto" }
"--text-wrap" = { syntax = "*", inherits = true, initial = "wrap" }
"--gradient-from-color" = { syntax = "<color>", inherits = false, initial = "transparent" }
"--gradient-to-color" = { syntax = "<color>", inherits = false, initial = "transparent" }
"--gradient-via-colors" = { syntax = "*", inherits = false }
"--border-color" = { syntax = "<color>", inherits = false, initial = "currentColor" }
"--border-top-color" = { syntax = "<color>", inherits = false, initial = "currentColor" }
"--border-right-color" = { syntax = "<color>", inherits = false, initial = "currentColor" }
"--border-bottom-color" = { syntax = "<color>", inherits = false, initial = "currentColor" }
"--border-left-color" = { syntax = "<color>", inherits = false, initial = "currentColor" }
"--divide-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--placeholder-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--bg-opacity" = { syntax = "<number>", inherits = false, initial = "1" }
"--transition-property" = { syntax = "*", inherits = false, initial = "all" }
"--transition-duration" = { syntax = "<time>", inherits = false, initial = "0s" }
"--transition-timing-function" = { syntax = "<timing-function>", inherits = false, initial = "ease" }
"--transition-delay" = { syntax = "<time>", inherits = false, initial = "0s" }
"--outline-offset" = { syntax = "<length>", inherits = false, initial = "0px" }
"--outline-color" = { syntax = "<color>", inherits = true, initial = "currentColor" }
"--text-decoration-color" = { syntax = "<color>", inherits = true, initial = "currentColor" }
"--underline-offset" = { syntax = "<length>", inherits = false, initial = "auto" }
"--text-decoration-thickness" = { syntax = "<length-percentage>", inherits = false, initial = "auto" }
"--text-decoration-skip-ink" = { syntax = "*", inherits = false, initial = "auto" }
"--flex" = { syntax = "*", inherits = false, initial = "0 1 auto" }
"--flex-grow" = { syntax = "<number>", inherits = false, initial = "0" }
"--flex-shrink" = { syntax = "<number>", inherits = false, initial = "1" }
"--flex-basis" = { syntax = "<flex-basis>", inherits = false, initial = "auto" }
"--order" = { syntax = "<integer>", inherits = false, initial = "0" }
"--z-index" = { syntax = "<integer>", inherits = false, initial = "0" }
"--object-fit" = { syntax = "*", inherits = false, initial = "fill" }
"--object-position" = { syntax = "<position>", inherits = false, initial = "50% 50%" }
"--overflow" = { syntax = "*", inherits = false, initial = "visible" }
"--overflow-x" = { syntax = "*", inherits = false, initial = "visible" }
"--overflow-y" = { syntax = "*", inherits = false, initial = "visible" }
"--scroll-behavior" = { syntax = "*", inherits = true, initial = "auto" }
"--overscroll" = { syntax = "*", inherits = false, initial = "auto" }
"--scroll-margin" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-margin-block" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-margin-inline" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-margin-top" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-margin-right" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-margin-bottom" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-margin-left" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding-block" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding-inline" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding-top" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding-right" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding-bottom" = { syntax = "<length>", inherits = false, initial = "0px" }
"--scroll-padding-left" = { syntax = "<length>", inherits = false, initial = "0px" }
"--place-self" = { syntax = "*", inherits = false, initial = "auto" }
"--place-items" = { syntax = "*", inherits = false, initial = "normal" }
"--place-content" = { syntax = "*", inherits = false, initial = "normal" }
"--grid-column" = { syntax = "*", inherits = false, initial = "none" }
"--grid-row" = { syntax = "*", inherits = false, initial = "none" }
"--mask-image" = { syntax = "<mask-source>", inherits = false, initial = "none" }
"--mask-position" = { syntax = "<position>", inherits = false, initial = "0% 0%" }
"--mask-size" = { syntax = "<length-percentage>", inherits = false, initial = "auto" }
"--mask-repeat" = { syntax = "<repeat-style>", inherits = false, initial = "no-repeat" }
"--mask-origin" = { syntax = "*", inherits = false, initial = "border-box" }
"--mask-clip" = { syntax = "*", inherits = false, initial = "border-box" }
"--mask-composite" = { syntax = "*", inherits = false, initial = "intersect" }
"--mask-mode" = { syntax = "*", inherits = false, initial = "match-source" }
"--container-padding-left" = { syntax = "<length>", inherits = false, initial = "0px" }
"--container-padding-right" = { syntax = "<length>", inherits = false, initial = "0px" }
"--aspect-w" = { syntax = "<number>", inherits = false, initial = "1" }
"--aspect-h" = { syntax = "<number>", inherits = false, initial = "1" }
"--line-clamp" = { syntax = "<integer>", inherits = false, initial = "none" }
"--break-after" = { syntax = "*", inherits = false, initial = "auto" }
"--break-before" = { syntax = "*", inherits = false, initial = "auto" }
"--break-inside" = { syntax = "*", inherits = false, initial = "auto" }
"--hyphens" = { syntax = "*", inherits = true, initial = "manual" }
"--list-style-image" = { syntax = "<url>", inherits = true, initial = "none" }
"--list-style-position" = { syntax = "*", inherits = true, initial = "outside" }
"--caption-side" = { syntax = "*", inherits = true, initial = "top" }
"--table-layout" = { syntax = "*", inherits = false, initial = "auto" }
"--border-collapse" = { syntax = "*", inherits = true, initial = "separate" }
"--visibility" = { syntax = "*", inherits = false, initial = "visible" }
"--position" = { syntax = "*", inherits = false, initial = "static" }
"--inset" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--inset-block" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--inset-inline" = { syntax = "<length-percentage>", inherits = false, initial = "0" }
"--top" = { syntax = "<length-percentage>", inherits = false, initial = "auto" }
"--right" = { syntax = "<length-percentage>", inherits = false, initial = "auto" }
"--bottom" = { syntax = "<length-percentage>", inherits = false, initial = "auto" }
"--left" = { syntax = "<length-percentage>", inherits = false, initial = "auto" }
"--float" = { syntax = "*", inherits = false, initial = "none" }
"--clear" = { syntax = "*", inherits = false, initial = "none" }
"--box-shadow" = { syntax = "<shadow>", inherits = false, initial = "none" }
"--clip-path" = { syntax = "<geometry-box>", inherits = false, initial = "none" }
"--isolation" = { syntax = "*", inherits = false, initial = "auto" }
"--mix-blend-mode" = { syntax = "*", inherits = false, initial = "normal" }
"--background-blend-mode" = { syntax = "*", inherits = false, initial = "normal" }
"--filter" = { syntax = "*", inherits = false, initial = "none" }
"--backdrop-filter" = { syntax = "*", inherits = false, initial = "none" }
"--will-change" = { syntax = "*", inherits = false, initial = "auto" }
"--touch-action" = { syntax = "*", inherits = false, initial = "auto" }
"--user-select" = { syntax = "*", inherits = false, initial = "auto" }
"--pointer-events" = { syntax = "*", inherits = false, initial = "auto" }
"--resize" = { syntax = "*", inherits = false, initial = "none" }
"--scroll-snap-type" = { syntax = "*", inherits = false, initial = "none" }
"--scroll-snap-align" = { syntax = "*", inherits = false, initial = "none" }
"--scroll-snap-stop" = { syntax = "*", inherits = false, initial = "normal" }
"--writing-mode" = { syntax = "*", inherits = true, initial = "horizontal-tb" }
"--text-orientation" = { syntax = "*", inherits = true, initial = "mixed" }
"--unicode-bidi" = { syntax = "*", inherits = false, initial = "normal" }
"--vertical-align" = { syntax = "<vertical-align>", inherits = false, initial = "baseline" }
"--appearance" = { syntax = "*", inherits = false, initial = "none" }
"--cursor" = { syntax = "*", inherits = true, initial = "auto" }
"--forced-colors" = { syntax = "*", inherits = false, initial = "auto" }
"--text-shadow" = { syntax = "<shadow>", inherits = false, initial = "0 0 #0000" }
"--text-shadow-2xs" = { syntax = "<shadow>", inherits = false, initial = "0 1px 0 rgb(0 0 0 / 0.15)" }
"--text-shadow-xs" = { syntax = "<shadow>", inherits = false, initial = "0 1px 1px rgb(0 0 0 / 0.2)" }
"--text-shadow-sm" = { syntax = "<shadow>", inherits = false, initial = "0 1px 0 rgb(0 0 0 / 0.075), 0 1px 1px rgb(0 0 0 / 0.075), 0 2px 2px rgb(0 0 0 / 0.075)" }
"--text-shadow-md" = { syntax = "<shadow>", inherits = false, initial = "0 1px 1px rgb(0 0 0 / 0.1), 0 1px 2px rgb(0 0 0 / 0.1), 0 2px 4px rgb(0 0 0 / 0.1)" }
"--text-shadow-lg" = { syntax = "<shadow>", inherits = false, initial = "0 1px 2px rgb(0 0 0 / 0.1), 0 3px 2px rgb(0 0 0 / 0.1), 0 4px 8px rgb(0 0 0 / 0.1)" }
