# -----------------------------------------------------------------------------
# [static]
# For simple, one-off classes that have a single, unchanging CSS rule.
# Format: class-name = "css-rule"
# -----------------------------------------------------------------------------
[static]
"-m-px" = "margin: -1px;"
"-mb-px" = "margin-bottom: -1px;"
"-ml-px" = "margin-left: -1px;"
"-mr-px" = "margin-right: -1px;"
"-mt-px" = "margin-top: -1px;"
"-mx-px" = "margin-left: -1px; margin-right: -1px;"
"-my-px" = "margin-top: -1px; margin-bottom: -1px;"
absolute = "position: absolute;"
accent-transparent = "accent-color: transparent;"
antialiased = "-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;"
appearance-none = "appearance: none;"
aspect-auto = "aspect-ratio: auto;"
aspect-square = "aspect-ratio: 1 / 1;"
aspect-video = "aspect-ratio: 16 / 9;"
basis-auto = "flex-basis: auto;"
basis-px = "flex-basis: 1px;"
bg-auto = "background-size: auto;"
bg-clip-border = "background-clip: border-box;"
bg-clip-content = "background-clip: content-box;"
bg-clip-padding = "background-clip: padding-box;"
bg-clip-text = "background-clip: text;"
bg-contain = "background-size: contain;"
bg-cover = "background-size: cover;"
bg-fixed = "background-attachment: fixed;"
bg-local = "background-attachment: local;"
bg-no-repeat = "background-repeat: no-repeat;"
bg-none = "background-image: none;"
bg-origin-border = "background-origin: border-box;"
bg-origin-content = "background-origin: content-box;"
bg-origin-padding = "background-origin: padding-box;"
bg-repeat = "background-repeat: repeat;"
bg-repeat-round = "background-repeat: round;"
bg-repeat-space = "background-repeat: space;"
bg-repeat-x = "background-repeat: repeat-x;"
bg-repeat-y = "background-repeat: repeat-y;"
bg-scroll = "background-attachment: scroll;"
block = "display: block;"
border = "border-width: 1px;"
border-b = "border-bottom-width: 1px;"
border-b-transparent = "border-bottom-color: transparent;"
border-collapse = "border-collapse: collapse;"
border-dashed = "border-style: dashed;"
border-double = "border-style: double;"
border-dotted = "border-style: dotted;"
border-hidden = "border-style: hidden;"
border-l = "border-left-width: 1px;"
border-l-transparent = "border-left-color: transparent;"
border-none = "border-style: none;"
border-r = "border-right-width: 1px;"
border-r-transparent = "border-right-color: transparent;"
border-separate = "border-collapse: separate;"
border-solid = "border-style: solid;"
border-spacing-0 = "border-spacing: 0;"
border-t = "border-top-width: 1px;"
border-t-transparent = "border-top-color: transparent;"
border-x = "border-left-width: 1px; border-right-width: 1px;"
border-y = "border-top-width: 1px; border-bottom-width: 1px;"
box-border = "box-sizing: border-box;"
box-content = "box-sizing: content-box;"
break-after-all = "break-after: all;"
break-after-auto = "break-after: auto;"
break-after-avoid = "break-after: avoid;"
break-after-avoid-page = "break-after: avoid-page;"
break-after-column = "break-after: column;"
break-after-left = "break-after: left;"
break-after-page = "break-after: page;"
break-after-right = "break-after: right;"
break-all = "word-break: break-all;"
break-before-all = "break-before: all;"
break-before-auto = "break-before: auto;"
break-before-avoid = "break-before: avoid;"
break-before-avoid-page = "break-before-avoid-page;"
break-before-column = "break-before: column;"
break-before-left = "break-before: left;"
break-before-page = "break-before: page;"
break-before-right = "break-before: right;"
break-inside-auto = "break-inside: auto;"
break-inside-avoid = "break-inside: avoid;"
break-inside-avoid-column = "break-inside: avoid-column;"
break-inside-avoid-page = "break-inside: avoid-page;"
break-inside-column = "break-inside: column;"
break-keep = "word-break: keep-all;"
break-normal = "overflow-wrap: normal; word-break: normal;"
break-words = "overflow-wrap: break-word;"
capitalize = "text-transform: capitalize;"
caption-bottom = "caption-side: bottom;"
caption-top = "caption-side: top;"
caret-transparent = "caret-color: transparent;"
col-auto = "grid-column: auto;"
col-span-full = "grid-column: 1 / -1;"
color-scheme-dark = "color-scheme: dark;"
color-scheme-light = "color-scheme: light;"
color-scheme-normal = "color-scheme: normal;"
columns-auto = "columns: auto;"
container = "width: 100%;"
container-type-inline-size = "container-type: inline-size;"
container-type-normal = "container-type: normal;"
container-type-size = "container-type: size;"
content-empty = "content: '';"
content-none = "content: none;"
contents = "display: contents;"
decoration-clone = "box-decoration-break: clone;"
decoration-slice = "box-decoration-break: slice;"
decoration-transparent = "text-decoration-color: transparent;"
diagonal-fractions = "font-variant-numeric: diagonal-fractions;"
divide-dashed = "border-style: dashed;"
divide-double = "border-style: double;"
divide-dotted = "border-style: dotted;"
divide-none = "border-style: none;"
divide-solid = "border-style: solid;"
divide-transparent = "border-color: transparent;"
fill-transparent = "fill: transparent;"
fixed = "position: fixed;"
flex = "display: flex;"
flex-1 = "flex: 1 1 0%;"
flex-auto = "flex: 1 1 auto;"
flex-col = "flex-direction: column;"
flex-col-reverse = "flex-direction: column-reverse;"
flex-initial = "flex: 0 1 auto;"
flex-none = "flex: none;"
flex-nowrap = "flex-wrap: nowrap;"
flex-row = "flex-direction: row;"
flex-row-reverse = "flex-direction: row-reverse;"
flex-wrap = "flex-wrap: wrap;"
flex-wrap-reverse = "flex-wrap: wrap-reverse;"
flow-root = "display: flow-root;"
from-transparent = "--gradient-from: transparent;"
grid = "display: grid;"
grow = "flex-grow: 1;"
grow-0 = "flex-grow: 0;"
hidden = "display: none;"
hyphens-auto = "hyphens: auto;"
hyphens-manual = "hyphens: manual;"
hyphens-none = "hyphens: none;"
inline = "display: inline;"
inline-block = "display: inline-block;"
inline-flex = "display: inline-flex;"
inline-grid = "display: inline-grid;"
inline-table = "display: inline-table;"
invisible = "visibility: hidden;"
isolate = "isolation: isolate;"
isolate-auto = "isolation: auto;"
italic = "font-style: italic;"
line-clamp-none = "overflow: visible; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: none;"
line-through = "text-decoration: line-through;"
lining-nums = "font-variant-numeric: lining-nums;"
list-decimal = "list-style-type: decimal;"
list-disc = "list-style-type: disc;"
list-image-none = "list-style-image: none;"
list-inside = "list-style-position: inside;"
list-item = "display: list-item;"
list-none = "list-style-type: none;"
list-outside = "list-style-position: outside;"
lowercase = "text-transform: lowercase;"
m-px = "margin: 1px;"
mb-px = "margin-bottom: 1px;"
mix-blend-color = "mix-blend-mode: color;"
mix-blend-color-burn = "mix-blend-mode: color-burn;"
mix-blend-color-dodge = "mix-blend-mode: color-dodge;"
mix-blend-darken = "mix-blend-mode: darken;"
mix-blend-difference = "mix-blend-mode: difference;"
mix-blend-exclusion = "mix-blend-mode: exclusion;"
mix-blend-hard-light = "mix-blend-mode: hard-light;"
mix-blend-hue = "mix-blend-mode: hue;"
mix-blend-lighten = "mix-blend-mode: lighten;"
mix-blend-luminosity = "mix-blend-mode: luminosity;"
mix-blend-multiply = "mix-blend-mode: multiply;"
mix-blend-normal = "mix-blend-mode: normal;"
mix-blend-overlay = "mix-blend-mode: overlay;"
mix-blend-saturation = "mix-blend-mode: saturation;"
mix-blend-screen = "mix-blend-mode: screen;"
mix-blend-soft-light = "mix-blend-mode: soft-light;"
ml-px = "margin-left: 1px;"
mr-px = "margin-right: 1px;"
mt-px = "margin-top: 1px;"
mx-px = "margin-left: 1px; margin-right: 1px;"
my-px = "margin-top: 1px; margin-bottom: 1px;"
none = "display: none;"
no-underline = "text-decoration: none;"
normal-case = "text-transform: none;"
normal-nums = "font-variant-numeric: normal;"
not-italic = "font-style: normal;"
not-sr-only = "position: static; width: auto; height: auto; padding: 0; margin: 0; overflow: visible; clip: auto; white-space: normal;"
oldstyle-nums = "font-variant-numeric: oldstyle-nums;"
ordinal = "font-variant-numeric: ordinal;"
outline = "outline-style: solid;"
outline-dashed = "outline-style: dashed;"
outline-double = "outline-style: double;"
outline-dotted = "outline-style: dotted;"
outline-hidden = "outline: 2px solid transparent; outline-offset: 2px;"
outline-none = "outline: 2px solid transparent; outline-offset: 2px;"
overline = "text-decoration: overline;"
overscroll-auto = "overscroll-behavior: auto;"
overscroll-contain = "overscroll-behavior: contain;"
overscroll-none = "overscroll-behavior: none;"
overscroll-x-auto = "overscroll-behavior-x: auto;"
overscroll-x-contain = "overscroll-behavior-x: contain;"
overscroll-x-none = "overscroll-behavior-x: none;"
overscroll-y-auto = "overscroll-behavior-y: auto;"
overscroll-y-contain = "overscroll-behavior-y: contain;"
overscroll-y-none = "overscroll-behavior-y: none;"
p-px = "padding: 1px;"
pb-px = "padding-bottom: 1px;"
pl-px = "padding-left: 1px;"
placeholder-transparent = "color: transparent;"
pointer-events-auto = "pointer-events: auto;"
pointer-events-none = "pointer-events: none;"
pr-px = "padding-right: 1px;"
proportional-nums = "font-variant-numeric: proportional-nums;"
pt-px = "padding-top: 1px;"
px-px = "padding-left: 1px; padding-right: 1px;"
py-px = "padding-top: 1px; padding-bottom: 1px;"
relative = "position: relative;"
resize = "resize: both;"
resize-none = "resize: none;"
resize-x = "resize: horizontal;"
resize-y = "resize: vertical;"
ring = "border-width: 1px; border-style: solid;"
ring-inset = "--ring-inset: inset;"
ring-offset-transparent = "--tw-ring-offset-color: transparent;"
ring-transparent = "box-shadow: 0 0 0 2px transparent;"
row-auto = "grid-row: auto;"
row-span-full = "grid-row: 1 / -1;"
scroll-auto = "scroll-behavior: auto;"
scroll-smooth = "scroll-behavior: smooth;"
scrollbar-auto = "scrollbar-width: auto;"
scrollbar-gutter-auto = "scrollbar-gutter: auto;"
scrollbar-gutter-stable = "scrollbar-gutter: stable;"
scrollbar-none = "::-webkit-scrollbar { display: none; } -ms-overflow-style: none; scrollbar-width: none;"
scrollbar-thin = "::-webkit-scrollbar { width: 8px; height: 8px; } ::-webkit-scrollbar-thumb { background-color: rgba(0,0,0,0.2); border-radius: 4px; }"
select-all = "user-select: all;"
select-auto = "user-select: auto;"
select-none = "user-select: none;"
select-text = "user-select: text;"
shadow = "box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);"
shadow-2xl = "box-shadow: 0 25px 50px -12px rgb(0 0 0 / 0.25);"
shadow-inner = "box-shadow: inset 0 2px 4px 0 rgb(0 0 0 / 0.05);"
shadow-lg = "box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);"
shadow-md = "box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);"
shadow-none = "box-shadow: 0 0 #0000;"
shadow-sm = "box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);"
shadow-transparent = "--tw-shadow-color: transparent;"
shadow-xl = "box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);"
shadow-xs = "box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);"
shrink = "flex-shrink: 1;"
shrink-0 = "flex-shrink: 0;"
slashed-zero = "font-variant-numeric: slashed-zero;"
space-x-px = "margin-left: 1px;"
space-x-reverse = "--space-x-reverse: 1;"
space-y-px = "margin-top: 1px;"
space-y-reverse = "--space-y-reverse: 1;"
sr-only = "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border-width: 0;"
sr-only-focusable = "position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border-width: 0; clip-path: inset(50%);"
stacked-fractions = "font-variant-numeric: stacked-fractions;"
static = "position: static;"
sticky = "position: sticky;"
stroke-transparent = "stroke: transparent;"
subpixel-antialiased = "-webkit-font-smoothing: auto; -moz-osx-font-smoothing: auto;"
table = "display: table;"
table-auto = "table-layout: auto;"
table-caption = "display: table-caption;"
table-cell = "display: table-cell;"
table-column = "display: table-column;"
table-column-group = "display: table-column-group;"
table-fixed = "table-layout: fixed;"
table-footer-group = "display: table-footer-group;"
table-header-group = "display: table-header-group;"
table-row = "display: table-row;"
table-row-group = "display: table-row-group;"
tabular-nums = "font-variant-numeric: tabular-nums;"
text-balance = "text-wrap: balance;"
text-clip = "text-overflow: clip;"
text-ellipsis = "text-overflow: ellipsis;"
text-gradient = "background-clip: text; -webkit-background-clip: text; color: transparent;"
text-pretty = "text-wrap: pretty;"
text-rendering-auto = "text-rendering: auto;"
text-rendering-geometric-precision = "text-rendering: geometricPrecision;"
text-rendering-geometricPrecision = "text-rendering: geometricPrecision;"
text-rendering-optimize-legibility = "text-rendering: optimizeLegibility;"
text-rendering-optimizeLegibility = "text-rendering: optimizeLegibility;"
text-rendering-optimize-speed = "text-rendering: optimizeSpeed;"
text-rendering-optimizeSpeed = "text-rendering: optimizeSpeed;"
to-transparent = "--gradient-to: transparent;"
transform = "transform: translate(var(--translate-x), var(--translate-y)) rotate(var(--rotate)) skewX(var(--skew-x)) skewY(var(--skew-y)) scaleX(var(--scale-x)) scaleY(var(--scale-y));"
transform-gpu = "transform: translate3d(var(--translate-x), var(--translate-y), 0) rotate(var(--rotate)) skewX(var(--skew-x)) skewY(var(--skew-y)) scaleX(var(--scale-x)) scaleY(var(--scale-y));"
transform-none = "transform: none;"
truncate = "overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"
underline = "text-decoration: underline;"
uppercase = "text-transform: uppercase;"
via-transparent = "--gradient-stops: var(--gradient-from), transparent, var(--gradient-to);"
view-transition-none = "view-transition-name: none;"
visible = "visibility: visible;"
whitespace-normal = "white-space: normal;"
whitespace-nowrap = "white-space: nowrap;"
whitespace-pre = "white-space: pre;"
whitespace-pre-line = "white-space: pre-line;"
whitespace-pre-wrap = "white-space: pre-wrap;"
writing-mode-horizontal-tb = "writing-mode: horizontal-tb;"
writing-mode-vertical-lr = "writing-mode: vertical-lr;"
writing-mode-vertical-rl = "writing-mode: vertical-rl;"
font-bold = "font-weight: 700;"
items-center = "align-items: center;"
justify-center = "justify-content: center;"
text-center = "text-align: center;"
border-inline = "border-inline-width: 1px;"
border-block = "border-block-width: 1px;"
border-is = "border-inline-start-width: 1px;"
border-ie = "border-inline-end-width: 1px;"
border-bs = "border-block-start-width: 1px;"
border-be = "border-block-end-width: 1px;"
border-inline-transparent = "border-inline-color: transparent;"
border-block-transparent = "border-block-color: transparent;"
rounded-bs = "border-start-start-radius: 0.25rem;"
rounded-be = "border-start-end-radius: 0.25rem;"
rounded-es = "border-end-start-radius: 0.25rem;"
rounded-ee = "border-end-end-radius: 0.25rem;"
