# -----------------------------------------------------------------------------
# [states]
# Defines pseudo-class variants that can be prefixed to any utility.
# e.g., "hover:bg-blue-500", "focus:ring-2", "first-child:p-0"
# Format: name = "pseudo-class"
# -----------------------------------------------------------------------------
[states]
hover = ":hover"
focus = ":focus"
focus-within = ":focus-within"
focus-visible = ":focus-visible"
active = ":active"
visited = ":visited"
target = ":target"
link = ":link"
empty = ":empty"
first = ":first-child"
last = ":last-child"
odd = ":nth-child(odd)"
even = ":nth-child(even)"
"only-child" = ":only-child"
"first-of-type" = ":first-of-type"
"last-of-type" = ":last-of-type"
"only-of-type" = ":only-of-type"
root = ":root"
disabled = ":disabled"
enabled = ":enabled"
checked = ":checked"
indeterminate = ":indeterminate"
default = ":default"
required = ":required"
optional = ":optional"
valid = ":valid"
invalid = ":invalid"
"in-range" = ":in-range"
"out-of-range" = ":out-of-range"
"placeholder-shown" = ":placeholder-shown"
autofill = ":autofill"
"read-only" = ":read-only"
"read-write" = ":read-write"
before = "::before"
after = "::after"
placeholder = "::placeholder"
file = "::file-selector-button"
marker = "::marker"
selection = "::selection"
"first-line" = "::first-line"
"first-letter" = "::first-letter"
backdrop = "::backdrop"
"group-hover" = ".group:hover &"
"group-focus" = ".group:focus &"
"group-focus-within" = ".group:focus-within &"
"group-focus-visible" = ".group:focus-visible &"
"group-active" = ".group:active &"
"group-visited" = ".group:visited &"
"group-disabled" = ".group:disabled &"
"group-checked" = ".group:checked &"
"group-first" = ".group:first-child &"
"group-last" = ".group:last-child &"
"group-odd" = ".group:nth-child(odd) &"
"group-even" = ".group:nth-child(even) &"
"group-open" = ".group[open] &"
"peer-hover" = ".peer:hover ~ &"
"peer-focus" = ".peer:focus ~ &"
"peer-focus-within" = ".peer:focus-within ~ &"
"peer-focus-visible" = ".peer:focus-visible ~ &"
"peer-active" = ".peer:active ~ &"
"peer-visited" = ".peer:visited ~ &"
"peer-disabled" = ".peer:disabled ~ &"
"peer-checked" = ".peer:checked ~ &"
"peer-indeterminate" = ".peer:indeterminate ~ &"
"peer-valid" = ".peer:valid ~ &"
"peer-invalid" = ".peer:invalid ~ &"
"peer-required" = ".peer:required ~ &"
"peer-optional" = ".peer:optional ~ &"
"peer-placeholder-shown" = ".peer:placeholder-shown ~ &"
"peer-read-only" = ".peer:read-only ~ &"
"peer-open" = ".peer[open] ~ &"
"has-checked" = ":has(:checked)"
"has-disabled" = ":has(:disabled)"
"has-focus" = ":has(:focus)"
"has-focus-visible" = ":has(:focus-visible)"
"has-focus-within" = ":has(:focus-within)"
"has-hover" = ":has(:hover)"
"has-active" = ":has(:active)"
"group-has-checked" = ".group:has(:checked) &"
"group-has-disabled" = ".group:has(:disabled) &"
"group-has-focus" = ".group:has(:focus) &"
"group-has-focus-visible" = ".group:has(:focus-visible) &"
"group-has-focus-within" = ".group:has(:focus-within) &"
"group-has-hover" = ".group:has(:hover) &"
"group-has-active" = ".group:has(:active) &"
"peer-has-checked" = ".peer:has(:checked) ~ &"
"peer-has-disabled" = ".peer:has(:disabled) ~ &"
"peer-has-focus" = ".peer:has(:focus) ~ &"
"peer-has-focus-visible" = ".peer:has(:focus-visible) ~ &"
"peer-has-focus-within" = ".peer:has(:focus-within) ~ &"
"peer-has-hover" = ".peer:has(:hover) ~ &"
"peer-has-active" = ".peer:has(:active) ~ &"
"not-disabled" = ":not(:disabled)"
"not-checked" = ":not(:checked)"
"not-focus" = ":not(:focus)"
"not-hover" = ":not(:hover)"
"not-first" = ":not(:first-child)"
"not-last" = ":not(:last-child)"
"not-only-child" = ":not(:only-child)"
dark = ".dark &"
light = ".light &"
ltr = "[dir='ltr'] &"
rtl = "[dir='rtl'] &"
open = "&[open]"
"data-active" = '&[data-active="true"]'
"data-open" = '&[data-state="open"]'
"data-closed" = '&[data-state="closed"]'
"aria-current" = '&[aria-current]'
"aria-busy" = '&[aria-busy="true"]'
"aria-checked" = '&[aria-checked="true"]'
"aria-disabled" = '&[aria-disabled="true"]'
"aria-expanded" = '&[aria-expanded="true"]'
"aria-hidden" = '&[aria-hidden="true"]'
"aria-pressed" = '&[aria-pressed="true"]'
"aria-readonly" = '&[aria-readonly="true"]'
"aria-required" = '&[aria-required="true"]'
"aria-selected" = '&[aria-selected="true"]'
"motion-reduce" = "@media (prefers-reduced-motion: reduce)"
"motion-safe" = "@media (prefers-reduced-motion: no-preference)"
print = "@media print"
portrait = "@media (orientation: portrait)"
landscape = "@media (orientation: landscape)"
"starting-style" = "@starting-style"
"supports-grid" = "@supports (display: grid)"
"supports-backdrop-filter" = "@supports (backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))"
